import React, { useMemo, useState } from 'react'
import { Link, NavLink, Navigate, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom'
import {
  Activity, ArrowRight, Bell, BookOpen, Calendar, CalendarCheck, ChevronDown, ChevronLeft, ChevronRight,
  CircleDollarSign, ClipboardList, Clock3, CreditCard, FileHeart, FileText, HeartPulse, HelpCircle, Home as HomeIcon,
  Hospital, Inbox, LayoutDashboard, LockKeyhole, LogOut, Menu, MessageCircle, Pill, Plus, Search, Settings,
  ShieldCheck, Sparkles, Stethoscope, TestTube2, UserRound, Users, WalletCards, X, Star, MapPin, Video,
  CheckCircle2, AlertCircle, TrendingUp, BadgeCheck, UserCog, BarChart3, LifeBuoy, History, Building2
} from 'lucide-react'
import { appointments, doctors, specialties, adminStats } from './data'
import { supabase, isSupabaseConfigured } from './supabase'
import { CareProvider, useCare } from './CareContext'
import { getProfile } from './careApi'
import BookingFlow from './BookingFlow'
import LiveAppointments from './LiveAppointments'
import { PatientBackendDashboard, PatientBackendWorkspace, DoctorBackendDashboard, DoctorBackendWorkspace, AdminBackendDashboard, AdminBackendWorkspace } from './PortalBackends'
import { createSupportRequest } from './portalApi'

const cls = (...v) => v.filter(Boolean).join(' ')
const money = v => new Intl.NumberFormat('en-PK', { style:'currency', currency:'PKR', maximumFractionDigits:0 }).format(v)

function Logo({ compact=false }) {
  return <Link className="brand" to="/"><span className="brandMark"><HeartPulse size={19}/></span>{!compact && <span>Medora</span>}</Link>
}

function Button({ children, variant='primary', className='', ...props }) {
  return <button className={cls('btn', `btn-${variant}`, className)} {...props}>{children}</button>
}

function PublicHeader() {
  const [open,setOpen] = useState(false)
  return <header className="publicHeader">
    <div className="container navInner">
      <Logo/>
      <nav className={cls('publicNav', open && 'open')} aria-label="Public navigation">
        <NavLink to="/doctors">Find doctors</NavLink><NavLink to="/specialties">Specialties</NavLink><NavLink to="/how-it-works">How it works</NavLink><NavLink to="/about">About</NavLink><NavLink to="/contact">Contact</NavLink>
      </nav>
      <div className="navActions"><Link className="textLink" to="/login">Sign in</Link><Link className="btn btn-primary" to="/register">Create account</Link></div>
      <button className="iconBtn mobileMenu" aria-label="Toggle menu" onClick={()=>setOpen(v=>!v)}>{open?<X/>:<Menu/>}</button>
    </div>
  </header>
}

function PublicFooter(){return <footer className="footer"><div className="container footerGrid"><div><Logo/><p>Thoughtful digital care for appointments, records and everyday health management.</p></div><div><strong>Patients</strong><Link to="/doctors">Find a doctor</Link><Link to="/specialties">Specialties</Link><Link to="/how-it-works">How it works</Link></div><div><strong>Company</strong><Link to="/about">About Medora</Link><Link to="/contact">Contact</Link><Link to="/faq">FAQ</Link></div><div><strong>Privacy & safety</strong><span>Privacy notice</span><span>Security standards</span><span>Accessibility</span></div></div><div className="container footerBottom"><span>© 2026 Medora Health</span><span>Demo portfolio product — not for emergency care.</span></div></footer>}

function Stars({rating}){return <span className="rating"><Star size={14} fill="currentColor"/> {rating}</span>}

function DoctorCard({doctor}){
  return <article className="doctorCard">
    <div className="doctorImage"><img src={doctor.image} alt=""/><span className="availableDot">Available</span></div>
    <div className="doctorBody"><div className="doctorTop"><div><h3>{doctor.name}</h3><p>{doctor.specialty}</p></div><Stars rating={doctor.rating}/></div>
      <div className="metaLine"><MapPin size={15}/>{doctor.clinic} · {doctor.location}</div>
      <div className="metaLine"><Clock3 size={15}/>{doctor.next}</div>
      <div className="doctorFoot"><div><small>Consultation</small><strong>{money(doctor.fee)}</strong></div><Link className="btn btn-secondary" to={`/doctors/${doctor.id}`}>View profile</Link></div>
    </div>
  </article>
}

function Home(){
  const { doctors } = useCare()
  const navigate=useNavigate(); const [query,setQuery]=useState('')
  return <><PublicHeader/><main>
    <section className="hero"><div className="container heroGrid"><div className="heroCopy"><span className="eyebrow"><Sparkles size={15}/> Trusted care, without the friction</span><h1>Healthcare that feels <em>human</em> from the first click.</h1><p>Find verified specialists, book in minutes and keep appointments, prescriptions and records together in one calm patient experience.</p>
      <div className="heroSearch"><Search size={19}/><input aria-label="Search doctors" placeholder="Doctor, specialty or symptom" value={query} onChange={e=>setQuery(e.target.value)}/><button onClick={()=>navigate(`/doctors?q=${encodeURIComponent(query)}`)}>Search care <ArrowRight size={17}/></button></div>
      <div className="trustRow"><div className="avatars">{doctors.slice(0,4).map(d=><img key={d.id} src={d.image} alt=""/>)}</div><div><strong>4.9/5 patient rating</strong><span>Across verified consultations</span></div></div>
    </div><div className="heroVisual"><img src="https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=88" alt="Doctor speaking with patient"/><div className="floatingCard appointmentFloat"><span className="miniIcon"><CalendarCheck size={18}/></span><div><small>Next appointment</small><strong>Dr. Sarah Malik</strong><span>Today · 5:30 PM</span></div></div><div className="floatingCard secureFloat"><ShieldCheck size={18}/><span>Private by design</span></div></div></div></section>

    <section className="container trustStrip"><span>Care built around clarity</span><div><BadgeCheck/> Verified clinicians</div><div><Clock3/> Live availability</div><div><ShieldCheck/> Protected health data</div><div><MessageCircle/> Secure messaging</div></section>

    <section className="section container"><div className="sectionHead"><div><span className="eyebrow">Explore care</span><h2>Start with the right specialty.</h2></div><Link to="/specialties">View all <ArrowRight size={16}/></Link></div><div className="specialtyGrid">{specialties.map(([name,desc,icon])=><Link className="specialtyCard" to={`/doctors?specialty=${name}`} key={name}><span>{icon}</span><div><strong>{name}</strong><small>{desc}</small></div><ChevronRight size={18}/></Link>)}</div></section>

    <section className="section softSection"><div className="container"><div className="sectionHead"><div><span className="eyebrow">Highly rated</span><h2>Doctors patients come back to.</h2></div><Link to="/doctors">Browse all doctors <ArrowRight size={16}/></Link></div><div className="doctorGrid">{doctors.slice(0,3).map(d=><DoctorCard key={d.id} doctor={d}/>)}</div></div></section>

    <section className="section container careJourney"><div className="journeyCopy"><span className="eyebrow">One connected journey</span><h2>From booking to follow-up, nothing gets lost.</h2><p>Medora keeps the care journey coherent: discover the right clinician, choose a real slot, prepare for your visit, then keep records and follow-up tasks in one place.</p><div className="featureStack"><div><span>01</span><div><strong>Choose with confidence</strong><p>Compare expertise, patient feedback, location, fee and next available time.</p></div></div><div><span>02</span><div><strong>Book without phone calls</strong><p>Select in-person or video care and confirm a slot in a short guided flow.</p></div></div><div><span>03</span><div><strong>Stay on top of care</strong><p>Appointments, prescriptions, lab results, invoices and messages remain organized.</p></div></div></div></div><div className="journeyPanel"><div className="miniDashboard"><div className="miniTop"><div><small>Good afternoon, Amina</small><strong>Your care overview</strong></div><Bell size={18}/></div><div className="miniAlert"><span><CalendarCheck/></span><div><strong>Cardiology follow-up</strong><small>Today · 5:30 PM · Medora Heart Centre</small></div><button>Details</button></div><div className="miniStats"><div><small>Prescriptions</small><strong>3 active</strong></div><div><small>Lab results</small><strong>2 new</strong></div><div><small>Care team</small><strong>4 doctors</strong></div></div><div className="miniRows"><div><span className="docDot">SM</span><div><strong>Dr. Sarah Malik</strong><small>Cardiology</small></div><span>Message</span></div><div><span className="docDot">HQ</span><div><strong>Dr. Hamza Qureshi</strong><small>Dermatology</small></div><span>View record</span></div></div></div></div></section>

    <section className="ctaBand"><div className="container"><div><span className="eyebrow light">Your health, organized</span><h2>Ready to make care feel simpler?</h2></div><Link className="btn btn-light" to="/register">Create your patient account <ArrowRight size={17}/></Link></div></section>
  </main><PublicFooter/></>
}

function FindDoctors(){
  const { doctors, catalogLoading, catalogError } = useCare()
  const location=useLocation()
  const params=new URLSearchParams(location.search)
  const [search,setSearch]=useState(params.get('q')||'')
  const [specialty,setSpecialty]=useState(params.get('specialty')||'All')
  const [gender,setGender]=useState('All')
  const [mode,setMode]=useState('All')
  const [sort,setSort]=useState('Recommended')
  const [maxFee,setMaxFee]=useState(6000)
  const [availableToday,setAvailableToday]=useState(false)
  const [highRating,setHighRating]=useState(false)
  const [videoOnly,setVideoOnly]=useState(false)
  const filtered=useMemo(()=>doctors
    .filter(d=>
      (!search||`${d.name} ${d.specialty} ${d.location}`.toLowerCase().includes(search.toLowerCase())) &&
      (specialty==='All'||d.specialty===specialty) &&
      (gender==='All'||d.gender===gender) &&
      (mode==='All'||d.mode.includes(mode)) &&
      Number(d.fee)<=maxFee &&
      (!availableToday||String(d.next||'').toLowerCase().startsWith('today')) &&
      (!highRating||Number(d.rating)>=4.8) &&
      (!videoOnly||d.mode.includes('Video'))
    )
    .sort((a,b)=>sort==='Fee: low to high'?a.fee-b.fee:sort==='Experience'?b.experience-a.experience:b.rating-a.rating),
    [doctors,search,specialty,gender,mode,sort,maxFee,availableToday,highRating,videoOnly])
  const clearFilters=()=>{setSearch('');setSpecialty('All');setGender('All');setMode('All');setSort('Recommended');setMaxFee(6000);setAvailableToday(false);setHighRating(false);setVideoOnly(false)}
  return <><PublicHeader/><main className="listingPage"><div className="container pageIntro"><span className="eyebrow">Verified clinicians</span><h1>Find care that fits your life.</h1><p>Search specialists, compare availability and book the format that works for you.</p></div><div className="container doctorSearchBar"><div><Search/><input aria-label="Search doctors directory" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Doctor, specialty or city"/></div><select aria-label="Specialty filter" value={specialty} onChange={e=>setSpecialty(e.target.value)}><option>All</option>{specialties.map(s=><option key={s[0]}>{s[0]}</option>)}</select><select aria-label="Gender filter" value={gender} onChange={e=>setGender(e.target.value)}><option>All</option><option>Female</option><option>Male</option></select><select aria-label="Consultation mode" value={mode} onChange={e=>setMode(e.target.value)}><option>All</option><option>Video</option><option>In-person</option></select></div><div className="container listingLayout"><aside className="filterPanel"><div className="filterTitle"><strong>Refine results</strong><button type="button" onClick={clearFilters}>Clear</button></div><label>Maximum fee <strong>{money(maxFee)}</strong><input type="range" min="2500" max="6000" step="100" value={maxFee} onChange={e=>setMaxFee(Number(e.target.value))}/></label><label className="check"><input type="checkbox" checked={availableToday} onChange={e=>setAvailableToday(e.target.checked)}/> Available today</label><label className="check"><input type="checkbox" checked={highRating} onChange={e=>setHighRating(e.target.checked)}/> 4.8+ rating</label><label className="check"><input type="checkbox" checked={videoOnly} onChange={e=>setVideoOnly(e.target.checked)}/> Video consultation</label><div className="infoBox"><ShieldCheck/><div><strong>Verified profiles</strong><p>Credentials and core profile information are reviewed before a clinician is listed.</p></div></div></aside><section className="results"><div className="resultsTop"><p><strong>{filtered.length}</strong> doctors match your search</p><select aria-label="Sort doctors" value={sort} onChange={e=>setSort(e.target.value)}><option>Recommended</option><option>Fee: low to high</option><option>Experience</option></select></div>{catalogError?<div role="alert" className="notice">{catalogError}</div>:catalogLoading?<p>Loading verified doctors…</p>:filtered.length?<div className="doctorGrid twoCols">{filtered.map(d=><DoctorCard key={d.id} doctor={d}/>)}</div>:<EmptyState icon={<Search/>} title="No doctors found" text="Try another specialty, city or consultation mode."/>}</section></div></main><PublicFooter/></>
}

function DoctorProfile(){const {id}=useParams(); const {doctors,catalogLoading,catalogError}=useCare(); const d=doctors.find(x=>x.id===id); const navigate=useNavigate(); if(!d)return <InfoPage eyebrow="Doctor directory" title={catalogLoading?'Loading doctor…':'Doctor unavailable'}><p>{catalogError||'Only verified clinicians can be booked.'}</p><Link to="/doctors">Back to doctors</Link></InfoPage>; return <><PublicHeader/><main className="profilePage"><div className="container breadcrumb"><Link to="/doctors"><ChevronLeft/>Back to doctors</Link></div><div className="container doctorProfileHero"><img src={d.image} alt=""/><div className="profileMain"><div className="profileTags"><span>{d.specialty}</span><span><BadgeCheck size={15}/> Verified</span></div><h1>{d.name}</h1><p>{d.clinic} · {d.location}</p><div className="profileMetrics"><div><strong>{d.rating}</strong><small>{d.reviews} patient reviews</small></div><div><strong>{d.experience} yrs</strong><small>Clinical experience</small></div><div><strong>{money(d.fee)}</strong><small>Consultation fee</small></div></div></div><div className="bookingSummary"><span className="statusPill"><span/> Next available</span><strong>{d.next}</strong><p>{d.mode.join(' · ')}</p><Button onClick={()=>navigate(`/patient/book?doctor=${d.id}`)}>Book appointment</Button></div></div><div className="container profileColumns"><section><h2>About {d.name.split(' ')[1]}</h2><p>{d.about}</p><h2>Areas of care</h2><div className="chipRow"><span>{d.specialty}</span><span>Preventive care</span><span>Follow-up care</span><span>Second opinions</span></div><h2>Patient feedback</h2><div className="reviewCard"><div><Stars rating={d.rating}/><strong>Clear, thoughtful and reassuring.</strong></div><p>“The consultation felt unhurried and the next steps were explained in a way I could actually follow.”</p><small>Verified patient · September 2026</small></div></section><aside><div className="sideCard"><h3>Clinic information</h3><div className="detailRow"><Building2/><div><strong>{d.clinic}</strong><span>{d.location}</span></div></div><div className="detailRow"><Video/><div><strong>Consultation options</strong><span>{d.mode.join(' and ')}</span></div></div><div className="detailRow"><MessageCircle/><div><strong>Languages</strong><span>{d.languages.join(', ')}</span></div></div></div><div className="sideCard"><h3>Credentials</h3><p>MBBS · FCPS · Board-certified specialist</p><p className="muted">Clinician profile information is provided by the care platform.</p></div></aside></div></main><PublicFooter/></>}

function InfoPage({title,eyebrow,children}){return <><PublicHeader/><main><div className="container simpleHero"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1></div><section className="container infoContent">{children}</section></main><PublicFooter/></>}
function Specialties(){return <InfoPage eyebrow="Clinical directory" title="Care for every stage of life."><div className="specialtyGrid large">{specialties.map(([n,d,i])=><Link className="specialtyCard" to={`/doctors?specialty=${n}`} key={n}><span>{i}</span><div><strong>{n}</strong><small>{d}</small></div><ArrowRight/></Link>)}</div></InfoPage>}
function HowItWorks(){return <InfoPage eyebrow="Simple by design" title="Book care in four clear steps."><div className="stepsGrid">{[['01','Search','Find doctors by specialty, city, care mode and availability.'],['02','Compare','Review expertise, fees, ratings and appointment options.'],['03','Book','Choose a real slot, consultation type and reason for visit.'],['04','Manage','Keep reminders, records, prescriptions and follow-ups organized.']].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></InfoPage>}
function About(){return <InfoPage eyebrow="About Medora" title="A calmer interface for complicated care."><div className="storyGrid"><div><h2>Designed around patient confidence.</h2><p>Medora is a portfolio healthcare product concept that brings discovery, scheduling and post-visit information into one coherent experience.</p><p>The visual system is intentionally restrained: strong hierarchy, generous whitespace, accessible contrast and calm interaction patterns instead of dashboard clutter.</p></div><img src="https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=1100&q=85" alt="Healthcare team"/></div></InfoPage>}
function Contact(){
  const [form,setForm]=useState({name:'',email:'',message:''}),[busy,setBusy]=useState(false),[status,setStatus]=useState('')
  const submit=async e=>{e.preventDefault();setBusy(true);setStatus('');try{await createSupportRequest(null,'Public support request',`Name: ${form.name}\nEmail: ${form.email}\n\n${form.message}`,'normal');setForm({name:'',email:'',message:''});setStatus('Your support request has been saved.')}catch(err){setStatus(err.message||'Unable to send your request.')}finally{setBusy(false)}}
  return <InfoPage eyebrow="Support" title="How can we help?"><div className="contactGrid"><div><h2>Patient support</h2><p>Questions about booking, account access or documents? Send a message and our support team will follow up.</p><div className="contactCard"><LifeBuoy/><div><strong>Support hours</strong><span>Mon–Sat · 8:00 AM–8:00 PM</span></div></div></div><form className="formCard" onSubmit={submit}><label>Name<input required value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))} placeholder="Your name"/></label><label>Email<input type="email" required value={form.email} onChange={e=>setForm(v=>({...v,email:e.target.value}))} placeholder="you@example.com"/></label><label>How can we help?<textarea required rows="5" maxLength={4000} value={form.message} onChange={e=>setForm(v=>({...v,message:e.target.value}))} placeholder="Tell us what you need…"/></label>{status&&<div className="notice"><p>{status}</p></div>}<Button type="submit" disabled={busy}>{busy?'Sending…':'Send message'}</Button></form></div></InfoPage>
}
function FAQ(){return <InfoPage eyebrow="Help center" title="Frequently asked questions."><div className="faqList">{['How do I reschedule an appointment?','Can I choose between video and in-person care?','Where can I find prescriptions and lab results?','How does doctor verification work?','Can I message my care team?'].map((q,i)=><details key={q} open={i===0}><summary>{q}<ChevronDown/></summary><p>Open the relevant appointment or care section in your patient portal. Medora keeps the next action visible and confirms changes before anything is saved.</p></details>)}</div></InfoPage>}

function AuthPage({register=false,forgot=false}){
  const nav=useNavigate()
  const [role,setRole]=useState('patient')
  const [fullName,setFullName]=useState('')
  const [email,setEmail]=useState('')
  const [password,setPassword]=useState('')
  const [busy,setBusy]=useState(false)
  const [message,setMessage]=useState('')
  const submit=async(e)=>{
    e.preventDefault()
    setMessage('')
    if(!isSupabaseConfigured){setMessage('Account service is unavailable. Please try again later.'); return}
    setBusy(true)
    try{
      if(forgot){
        const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin+'/login'})
        if(error) throw error
        setMessage('Password reset instructions have been sent to your email.')
        return
      }
      if(register){
        if(role!=='patient'){setMessage('Clinician and admin accounts require approval. Register a patient account or open a role demo.'); return}
        const {data,error}=await supabase.auth.signUp({email,password,options:{data:{full_name:fullName}}})
        if(error) throw error
        if(data.session){nav('/patient')}
        else setMessage('Account created. Check your email to confirm access, then sign in.')
        return
      }
      const {data,error}=await supabase.auth.signInWithPassword({email,password})
      if(error) throw error
      const liveProfile=await getProfile(data.user.id)
      if(liveProfile.status!=='active') throw new Error('Your account is not active. Contact support.')
      const liveRole=liveProfile.role
      localStorage.setItem('medoraRole',liveRole)
      nav('/'+liveRole)
    }catch(error){
      setMessage(error.message||'Unable to complete this request.')
    }finally{
      setBusy(false)
    }
  }
  const openDemo=()=>{localStorage.setItem('medoraRole',role); nav('/'+role)}
  return <div className="authPage"><div className="authAside"><Logo/><div><span className="eyebrow light">Care, connected</span><h1>{forgot?'Reset your access.':register?'One account for your care journey.':'Welcome back to Medora.'}</h1><p>Securely manage appointments, records, prescriptions and conversations from one thoughtful workspace.</p></div><small>Portfolio demo · Never use real medical information.</small></div><div className="authMain"><div className="authBox"><Link className="backHome" to="/"><ChevronLeft/> Back home</Link><h2>{forgot?'Forgot password':register?'Create your account':'Sign in'}</h2><p>{forgot?'We’ll send reset instructions to your email.':register?'Patient registration is open. Clinician and admin access requires approval.':'Sign in with Supabase Auth, or open a role demo to review the product.'}</p>{!forgot&&<div className="roleTabs">{['patient','doctor','admin'].map(r=><button type="button" className={role===r?'active':''} onClick={()=>setRole(r)} key={r}>{r[0].toUpperCase()+r.slice(1)}</button>)}</div>}<form onSubmit={submit}>{register&&<label>Full name<input required value={fullName} onChange={e=>setFullName(e.target.value)} placeholder="Amina Khan"/></label>}<label>Email address<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="amina@example.com"/></label>{!forgot&&<label>Password<input type="password" required minLength="6" value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••"/></label>}{message&&<div className="notice"><AlertCircle/><p>{message}</p></div>}<Button type="submit" disabled={busy}>{busy?'Please wait…':forgot?'Send reset link':register?'Create secure account':'Sign in securely'}</Button></form>{!forgot&&<><Button type="button" variant="secondary" className="authDemoButton" onClick={openDemo}>Open {role} demo</Button><p className="authSwitch">{register?'Already have an account?':'New to Medora?'} <Link to={register?'/login':'/register'}>{register?'Sign in':'Create account'}</Link></p></>}{!register&&!forgot&&<Link className="forgotLink" to="/forgot-password">Forgot password?</Link>}</div></div></div>
}

const patientNav=[['/patient',LayoutDashboard,'Overview'],['/patient/book',CalendarCheck,'Book appointment'],['/patient/appointments',Calendar,'Appointments'],['/patient/doctors',Stethoscope,'My doctors'],['/patient/messages',MessageCircle,'Messages'],['/patient/records',FileHeart,'Medical records'],['/patient/prescriptions',Pill,'Prescriptions'],['/patient/labs',TestTube2,'Lab results'],['/patient/billing',WalletCards,'Bills & payments'],['/patient/insurance',ShieldCheck,'Insurance'],['/patient/notifications',Bell,'Notifications'],['/patient/profile',UserRound,'Profile'],['/patient/settings',Settings,'Settings'],['/patient/security',LockKeyhole,'Security']]
const doctorNav=[['/doctor',LayoutDashboard,'Overview'],['/doctor/appointments',Calendar,'Today’s appointments'],['/doctor/requests',Inbox,'Appointment requests'],['/doctor/patients',Users,'Patients'],['/doctor/schedule',Clock3,'Schedule'],['/doctor/notes',ClipboardList,'Consultation notes'],['/doctor/prescriptions',Pill,'Prescriptions'],['/doctor/records',FileHeart,'Records'],['/doctor/messages',MessageCircle,'Messages'],['/doctor/earnings',CircleDollarSign,'Earnings'],['/doctor/profile',UserRound,'Profile'],['/doctor/settings',Settings,'Settings']]
const adminNav=[['/admin',LayoutDashboard,'Overview'],['/admin/doctors',Stethoscope,'Doctors'],['/admin/patients',Users,'Patients'],['/admin/appointments',Calendar,'Appointments'],['/admin/specialties',Activity,'Specialties'],['/admin/reviews',Star,'Reviews'],['/admin/payments',CreditCard,'Payments'],['/admin/analytics',BarChart3,'Analytics'],['/admin/support',LifeBuoy,'Support'],['/admin/users',UserCog,'User status'],['/admin/audit',History,'Audit activity']]

function RoleShell({role,nav,children}){
  const {profile,session}=useCare()
  const liveName=profile?.role===role?profile.full_name:null
  const [mobile,setMobile]=useState(false)
  const location=useLocation()
  const title=nav.find(n=>n[0]===location.pathname)?.[2]||'Workspace'
  const searchTarget=role==='patient'?'/patient/doctors':role==='doctor'?'/doctor/patients':'/admin/users'
  const alertTarget=role==='patient'?'/patient/notifications':role==='doctor'?'/doctor/messages':'/admin/support'
  const profileTarget=role==='patient'?'/patient/profile':role==='doctor'?'/doctor/profile':'/admin/users'
  const initials=(liveName|| (role==='patient'?'Amina Khan':role==='doctor'?'Sarah Malik':'Medora Admin')).split(' ').filter(Boolean).slice(-2).map(x=>x[0]).join('').toUpperCase()
  return <div className="portal"><aside className={cls('sidebar',mobile&&'open')}><div className="sideTop"><Logo/><button aria-label="Close navigation" className="iconBtn closeSide" onClick={()=>setMobile(false)}><X/></button></div><div className="roleBadge"><span>{initials}</span><div><strong>{liveName || (role==='patient'?'Patient demo':role==='doctor'?'Doctor demo':'Admin demo')}</strong><small>{role[0].toUpperCase()+role.slice(1)} workspace</small></div></div><nav>{nav.map(([to,Icon,label])=><NavLink end={to===`/${role}`} to={to} key={to} onClick={()=>setMobile(false)}><Icon size={18}/>{label}</NavLink>)}</nav><div className="sideBottom"><Link to="/" onClick={()=>{localStorage.removeItem('medoraRole'); supabase?.auth.signOut()}}><LogOut size={18}/> Exit workspace</Link></div></aside><div className="portalMain"><header className="portalHeader"><button aria-label="Open navigation" className="iconBtn openSide" onClick={()=>setMobile(true)}><Menu/></button><div><small>{role[0].toUpperCase()+role.slice(1)} portal</small><h1>{title}</h1></div><div className="portalActions"><Link className="searchMini" to={searchTarget}><Search size={17}/> Search</Link><Link aria-label="Open alerts" className="iconBtn" to={alertTarget}><Bell size={19}/><span className="notificationDot"/></Link><Link aria-label="Open profile" className="profileMini" to={profileTarget}>{initials}</Link></div></header>{!session&&<div className="demoBanner"><ShieldCheck size={16}/><span><strong>Synthetic demo data</strong> — explore the full interface safely; sign in to use the live Supabase workflows.</span></div>}<main className="portalContent">{children}</main></div></div>
}

function Metric({icon:Icon,label,value,meta}){return <div className="metricCard"><div className="metricIcon"><Icon/></div><div><span>{label}</span><strong>{value}</strong><small>{meta}</small></div></div>}
function SectionTitle({title,action}){return <div className="panelTitle"><h2>{title}</h2>{action&&<button>{action}<ArrowRight/></button>}</div>}
function EmptyState({icon,title,text}){return <div className="emptyState"><span>{icon}</span><h3>{title}</h3><p>{text}</p></div>}

function PatientDashboard(){return <RoleShell role="patient" nav={patientNav}><div className="welcomeLine"><div><span className="eyebrow">Saturday, October 3</span><h2>Good afternoon, Amina.</h2><p>Here’s what needs your attention today.</p></div><Link className="btn btn-primary" to="/patient/book"><Plus/> Book appointment</Link></div><div className="metricsGrid"><Metric icon={CalendarCheck} label="Next appointment" value="Tomorrow · 5:30 PM" meta="Dr. Sarah Malik · Cardiology"/><Metric icon={Pill} label="Active prescriptions" value="3 medications" meta="1 refill due this week"/><Metric icon={TestTube2} label="New lab results" value="2 results" meta="Reviewed by your doctor"/><Metric icon={MessageCircle} label="Unread messages" value="2 messages" meta="From your care team"/></div><div className="dashboardGrid"><section className="panel span2"><SectionTitle title="Upcoming care" action="All appointments"/><div className="appointmentFeature"><div className="dateTile"><strong>04</strong><span>OCT</span></div><div className="appointmentInfo"><span className="statusPill green">Confirmed</span><h3>Cardiology follow-up</h3><p>Dr. Sarah Malik · Medora Heart Centre</p><div><span><Clock3/>5:30 PM</span><span><MapPin/>Lahore</span></div></div><div className="appointmentActions"><Button variant="secondary">Reschedule</Button><Button>View details</Button></div></div></section><section className="panel"><SectionTitle title="Care tasks"/><div className="taskList"><label><input type="checkbox"/> Upload previous ECG report</label><label><input type="checkbox"/> Confirm insurance details</label><label className="done"><input type="checkbox" defaultChecked/> Complete pre-visit form</label></div></section><section className="panel span2"><SectionTitle title="Recent health activity" action="View records"/><div className="timeline"><div><span><TestTube2/></span><div><strong>Lipid profile result available</strong><p>Reviewed by Dr. Sarah Malik</p></div><small>Today</small></div><div><span><Pill/></span><div><strong>Prescription renewed</strong><p>Atorvastatin 20 mg</p></div><small>Sep 28</small></div><div><span><MessageCircle/></span><div><strong>New care team message</strong><p>“Your results look stable…”</p></div><small>Sep 26</small></div></div></section><section className="panel"><SectionTitle title="Care team"/><div className="careTeam">{doctors.slice(0,3).map(d=><div key={d.id}><img src={d.image} alt=""/><div><strong>{d.name}</strong><small>{d.specialty}</small></div><button><MessageCircle/></button></div>)}</div></section></div></RoleShell>}

function BookingPage(){return <RoleShell role="patient" nav={patientNav}><BookingFlow/></RoleShell>}
function PatientAppointments(){return <RoleShell role="patient" nav={patientNav}><LiveAppointments/></RoleShell>}

const patientCollections={
  '/patient/doctors':['My doctors','Your established care team.','doctor'],
  '/patient/messages':['Messages','Secure conversations with your care team.','messages'],
  '/patient/records':['Medical records','A chronological view of diagnoses, notes and shared documents.','records'],
  '/patient/prescriptions':['Prescriptions','Active and previous medications with refill status.','prescriptions'],
  '/patient/labs':['Lab results','Results, reference ranges and clinician review status.','labs'],
  '/patient/billing':['Bills & payments','Invoices, receipts and payment history.','billing'],
  '/patient/insurance':['Insurance','Coverage details used for eligible appointments.','insurance'],
  '/patient/notifications':['Notifications','Appointment reminders and care updates.','notifications'],
  '/patient/profile':['Profile','Personal and emergency contact details.','profile'],
  '/patient/settings':['Settings','Communication, accessibility and portal preferences.','settings'],
  '/patient/security':['Security','Password, sessions and account protection.','security']
}
function PatientCollection(){const cfg=patientCollections[useLocation().pathname]||patientCollections['/patient/records']; return <RoleShell role="patient" nav={patientNav}><GenericWorkspace title={cfg[0]} subtitle={cfg[1]} type={cfg[2]}/></RoleShell>}

function GenericWorkspace({title,subtitle,type}){
 const content={
 doctor:<div className="doctorGrid twoCols">{doctors.slice(0,4).map(d=><DoctorCard doctor={d} key={d.id}/>)}</div>,
 messages:<div className="messageShell"><div className="conversationList">{doctors.slice(0,4).map((d,i)=><button className={i===0?'active':''} key={d.id}><img src={d.image} alt=""/><div><strong>{d.name}</strong><small>{i===0?'Your results look stable.':'Appointment follow-up'}</small></div><span>{i===0?'2':''}</span></button>)}</div><div className="chatPanel"><div className="chatHead"><img src={doctors[0].image} alt=""/><div><strong>{doctors[0].name}</strong><small>Usually replies within 1 business day</small></div></div><div className="chatBody"><div className="bubble theirs">Your latest ECG looks stable. Please keep the current medication schedule until our visit tomorrow.</div><div className="bubble mine">Thank you. I’ve uploaded the previous report as well.</div></div><div className="chatInput"><input placeholder="Write a secure message…"/><button><ArrowRight/></button></div></div></div>,
 records:<div className="recordList">{[['Sep 18','Dermatology consultation','Acne follow-up · Dr. Hamza Qureshi'],['Aug 21','Psychiatry consultation','Wellbeing follow-up · Dr. Noor Fatima'],['Jul 03','Cardiology diagnostic note','Routine ECG reviewed · Dr. Sarah Malik']].map(x=><div key={x[0]}><span>{x[0]}</span><div><strong>{x[1]}</strong><small>{x[2]}</small></div><button>Open record</button></div>)}</div>,
 prescriptions:<div className="cardGrid">{[['Atorvastatin','20 mg · Once daily','2 refills'],['Vitamin D3','2000 IU · Once daily','Active'],['Cetirizine','10 mg · As needed','Ends Oct 14']].map(x=><article className="infoCard" key={x[0]}><Pill/><span>Active prescription</span><h3>{x[0]}</h3><p>{x[1]}</p><small>{x[2]}</small><button>View details</button></article>)}</div>,
 labs:<div className="cardGrid">{[['Lipid profile','Reviewed','Oct 02'],['Complete blood count','Reviewed','Oct 01'],['Vitamin D','New','Sep 29']].map(x=><article className="infoCard" key={x[0]}><TestTube2/><span>{x[1]}</span><h3>{x[0]}</h3><p>Results available with reference ranges and clinician notes.</p><small>{x[2]}</small><button>View result</button></article>)}</div>,
 billing:<div className="billingGrid"><Metric icon={WalletCards} label="Outstanding balance" value="PKR 4,500" meta="1 invoice due"/><Metric icon={CreditCard} label="Saved payment method" value="•••• 4242" meta="Visa · expires 08/29"/><div className="panel span2"><SectionTitle title="Recent invoices"/><div className="listRows"><div><span>Cardiology consultation</span><strong>PKR 4,500</strong><small>Due Oct 4</small></div><div><span>Dermatology consultation</span><strong>PKR 3,200</strong><small>Paid Sep 18</small></div></div></div></div>,
 insurance:<div className="insuranceCard"><ShieldCheck/><span>Primary coverage</span><h2>Sehat Secure Plus</h2><p>Policy •••• 4218 · Active through Jun 2027</p><div><span>Outpatient care</span><strong>Covered</strong></div><div><span>Teleconsultation</span><strong>Covered</strong></div><div><span>Annual remaining limit</span><strong>PKR 82,000</strong></div><Button variant="secondary">Update insurance</Button></div>,
 notifications:<div className="notificationList">{[['Appointment reminder','Your cardiology visit is tomorrow at 5:30 PM.','10 min ago'],['Lab result reviewed','Dr. Sarah Malik reviewed your lipid profile.','2 hours ago'],['Prescription renewed','Your Atorvastatin prescription has been renewed.','Sep 28']].map(x=><div key={x[0]}><span><Bell/></span><div><strong>{x[0]}</strong><p>{x[1]}</p></div><small>{x[2]}</small></div>)}</div>,
 profile:<ProfileForm/>, settings:<SettingsView/>, security:<SecurityView/>
 }
 return <><div className="contentHeader"><div><h2>{title}</h2><p>{subtitle}</p></div>{['records','labs'].includes(type)&&<Button variant="secondary"><Plus/>Upload document</Button>}</div>{content[type]}</>
}
function ProfileForm(){return <form className="settingsForm" onSubmit={e=>{e.preventDefault(); alert('Profile saved — demo')}}><div className="formSection"><h3>Personal information</h3><div className="formGrid"><label>Full name<input defaultValue="Amina Khan"/></label><label>Date of birth<input type="date" defaultValue="1998-04-12"/></label><label>Phone<input defaultValue="+92 300 0000000"/></label><label>City<input defaultValue="Lahore"/></label></div></div><div className="formSection"><h3>Emergency contact</h3><div className="formGrid"><label>Name<input defaultValue="Sara Khan"/></label><label>Relationship<input defaultValue="Sister"/></label><label>Phone<input defaultValue="+92 301 0000000"/></label></div></div><Button type="submit">Save changes</Button></form>}
function SettingsView(){return <div className="settingsForm"><div className="formSection"><h3>Communication preferences</h3>{['Appointment reminders','Prescription reminders','Lab result alerts','Care team messages'].map((x,i)=><label className="toggleRow" key={x}><span><strong>{x}</strong><small>{i===0?'Email and SMS':'Portal notification'}</small></span><input type="checkbox" defaultChecked={i<3}/></label>)}</div><div className="formSection"><h3>Accessibility</h3><label>Text size<select><option>Default</option><option>Large</option></select></label></div></div>}
function SecurityView(){return <div className="settingsForm"><div className="securityHero"><ShieldCheck/><div><h3>Account protection</h3><p>Your demo account has multi-factor authentication enabled.</p></div><span>Protected</span></div><div className="formSection"><h3>Active sessions</h3><div className="sessionRow"><div><strong>Chrome on Windows</strong><small>Lahore · Current session</small></div><span>Active now</span></div><div className="sessionRow"><div><strong>Safari on iPhone</strong><small>Lahore · Sep 30</small></div><button>Sign out</button></div></div><Button variant="secondary">Change password</Button></div>}

function DoctorDashboard(){return <RoleShell role="doctor" nav={doctorNav}><div className="welcomeLine"><div><span className="eyebrow">Clinical workspace</span><h2>Good afternoon, Dr. Sarah.</h2><p>You have 7 consultations and 3 follow-up tasks today.</p></div><Button><Plus/>Add availability</Button></div><div className="metricsGrid"><Metric icon={Calendar} label="Appointments today" value="7" meta="Next at 4:15 PM"/><Metric icon={Inbox} label="Pending requests" value="5" meta="2 need review today"/><Metric icon={Users} label="Active patients" value="284" meta="12 seen this month"/><Metric icon={CircleDollarSign} label="This month" value="PKR 386K" meta="+8.4% from September"/></div><div className="dashboardGrid"><section className="panel span2"><SectionTitle title="Today’s schedule" action="Full calendar"/><div className="scheduleList">{[['4:15 PM','Hassan Ali','New consultation','In-person'],['5:30 PM','Amina Khan','Follow-up','In-person'],['7:00 PM','Mariam Noor','Results review','Video']].map((x,i)=><div className={i===1?'current':''} key={x[0]}><strong>{x[0]}</strong><span className="avatarText">{x[1].split(' ').map(n=>n[0]).join('')}</span><div><strong>{x[1]}</strong><small>{x[2]} · {x[3]}</small></div><button>Open chart</button></div>)}</div></section><section className="panel"><SectionTitle title="Clinical tasks"/><div className="taskList"><label><input type="checkbox"/> Review 2 lab results</label><label><input type="checkbox"/> Sign 1 prescription</label><label><input type="checkbox"/> Complete 3 visit notes</label></div></section><section className="panel span2"><SectionTitle title="Patient activity"/><div className="patientTable"><div><strong>Amina Khan</strong><span>Cardiology follow-up</span><small>Tomorrow · 5:30 PM</small><button>View</button></div><div><strong>Hassan Ali</strong><span>Hypertension assessment</span><small>Today · 4:15 PM</small><button>View</button></div><div><strong>Mariam Noor</strong><span>Lab review</span><small>Today · 7:00 PM</small><button>View</button></div></div></section><section className="panel"><SectionTitle title="Weekly volume"/><div className="bars">{[42,58,48,75,68,34,22].map((h,i)=><div key={i}><span style={{height:`${h}%`}}/><small>{['M','T','W','T','F','S','S'][i]}</small></div>)}</div></section></div></RoleShell>}

const doctorCollections={
 '/doctor/appointments':['Today’s appointments','Your clinical schedule and consultation status.','schedule'], '/doctor/requests':['Appointment requests','Review new requests before they enter your schedule.','requests'], '/doctor/patients':['Patients','Search patient profiles and recent clinical activity.','patients'], '/doctor/schedule':['Schedule','Manage working hours, leave and appointment availability.','availability'], '/doctor/notes':['Consultation notes','Complete and sign clinical notes.','notes'], '/doctor/prescriptions':['Prescriptions','Draft, review and sign medications.','rx'], '/doctor/records':['Records','Clinical documents and patient history.','records'], '/doctor/messages':['Messages','Secure patient and care-team conversations.','messages'], '/doctor/earnings':['Earnings','Consultation revenue and settlement overview.','earnings'], '/doctor/profile':['Doctor profile','Public profile, credentials and consultation details.','doctorprofile'], '/doctor/settings':['Settings','Clinical and workspace preferences.','doctorsettings']
}
function DoctorCollection(){const c=doctorCollections[useLocation().pathname]; return <RoleShell role="doctor" nav={doctorNav}><DoctorWorkspace title={c[0]} subtitle={c[1]} type={c[2]}/></RoleShell>}
function DoctorWorkspace({title,subtitle,type}){const common=<div className="clinicalTable"><div className="tableRow tableHead"><span>Patient</span><span>Care reason</span><span>Schedule</span><span>Status</span><span></span></div>{[['Amina Khan','Cardiology follow-up','Oct 04 · 5:30 PM','Confirmed'],['Hassan Ali','Hypertension assessment','Today · 4:15 PM','Checked in'],['Mariam Noor','Lab results review','Today · 7:00 PM','Video']].map(x=><div className="tableRow" key={x[0]}><span><strong>{x[0]}</strong><small>ID PT-{Math.floor(x[0].length*317)}</small></span><span>{x[1]}</span><span>{x[2]}</span><span><span className="badge confirmed">{x[3]}</span></span><span><button>Open</button></span></div>)}</div>; const content={schedule:common,requests:<div className="requestGrid">{[['Nadia Aslam','Chest discomfort','Tomorrow · 9:00 AM'],['Usman Tariq','Blood pressure review','Mon · 2:30 PM'],['Zoya Hassan','Second opinion','Tue · 11:30 AM']].map(x=><article key={x[0]}><span className="avatarText">{x[0].split(' ').map(n=>n[0]).join('')}</span><h3>{x[0]}</h3><p>{x[1]}</p><small>{x[2]}</small><div><Button variant="secondary">Decline</Button><Button>Accept</Button></div></article>)}</div>,patients:common,availability:<AvailabilityEditor/>,notes:<NotesWorkspace/>,rx:<PrescriptionEditor/>,records:common,messages:<GenericWorkspace title="" subtitle="" type="messages"/>,earnings:<EarningsView/>,doctorprofile:<DoctorProfileEditor/>,doctorsettings:<SettingsView/>}; return <><div className="contentHeader"><div><h2>{title}</h2><p>{subtitle}</p></div>{['availability','rx'].includes(type)&&<Button><Plus/>{type==='availability'?'Add hours':'New prescription'}</Button>}</div>{content[type]}</>}
function AvailabilityEditor(){return <div className="availabilityPanel">{['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map((d,i)=><div key={d}><div><strong>{d}</strong><small>{i<5?'Available':'Off'}</small></div>{i<5?<><input defaultValue={i===4?'10:00':'09:00'}/><span>to</span><input defaultValue={i===4?'15:00':'18:00'}/><button>+ Break</button></>:<Button variant="ghost">Set hours</Button>}</div>)}</div>}
function NotesWorkspace(){return <div className="notesLayout"><div className="patientContext"><span className="avatarText">AK</span><h3>Amina Khan</h3><p>28 years · Female</p><hr/><small>Reason for visit</small><strong>Cardiology follow-up</strong><small>Relevant conditions</small><strong>Hypertension</strong></div><form className="noteEditor"><label>Subjective<textarea rows="4" defaultValue="Patient reports improved exercise tolerance and no new chest pain."/></label><label>Assessment<textarea rows="4" defaultValue="Stable follow-up. Blood pressure within target range."/></label><label>Plan<textarea rows="4" defaultValue="Continue current medication. Repeat lipid profile in 3 months."/></label><div><Button variant="secondary">Save draft</Button><Button>Sign note</Button></div></form></div>}
function PrescriptionEditor(){return <div className="settingsForm"><div className="formSection"><div className="formGrid"><label>Patient<select><option>Amina Khan</option><option>Hassan Ali</option></select></label><label>Medication<input placeholder="Search medication" defaultValue="Atorvastatin"/></label><label>Dose<input defaultValue="20 mg"/></label><label>Frequency<select><option>Once daily</option><option>Twice daily</option></select></label><label>Duration<input defaultValue="90 days"/></label><label>Refills<input defaultValue="2"/></label></div><label>Instructions<textarea rows="3" defaultValue="Take in the evening with water."/></label></div><Button>Review & sign prescription</Button></div>}
function EarningsView(){return <div className="billingGrid"><Metric icon={CircleDollarSign} label="October earnings" value="PKR 386K" meta="+8.4% vs September"/><Metric icon={CalendarCheck} label="Completed visits" value="92" meta="This month"/><Metric icon={WalletCards} label="Next settlement" value="PKR 74K" meta="Oct 7"/><div className="panel span2"><SectionTitle title="Settlement history"/><div className="listRows"><div><span>Sep 30 settlement</span><strong>PKR 312,400</strong><small>Paid</small></div><div><span>Sep 15 settlement</span><strong>PKR 148,200</strong><small>Paid</small></div></div></div></div>}
function DoctorProfileEditor(){return <div className="profileEditor"><img src={doctors[0].image} alt=""/><ProfileForm/></div>}

function AdminDashboard(){return <RoleShell role="admin" nav={adminNav}><div className="welcomeLine"><div><span className="eyebrow">Platform operations</span><h2>Medora control center.</h2><p>Monitor access, care operations and platform health.</p></div><Button><Plus/>Invite clinician</Button></div><div className="metricsGrid">{adminStats.map((x,i)=><Metric key={x[0]} icon={[Users,Stethoscope,Calendar,TrendingUp][i]} label={x[0]} value={x[1]} meta={x[2]}/>)}</div><div className="dashboardGrid"><section className="panel span2"><SectionTitle title="Doctor verification queue" action="Manage doctors"/><div className="verificationList">{[['Dr. Hira Sheikh','Endocrinology','Credentials received'],['Dr. Ali Raza','ENT','License check pending'],['Dr. Maha Khan','Gynecology','Ready for approval']].map((x,i)=><div key={x[0]}><span className="avatarText">{x[0].split(' ').slice(1).map(n=>n[0]).join('')}</span><div><strong>{x[0]}</strong><small>{x[1]} · {x[2]}</small></div><span className={cls('badge',i===2?'confirmed':'pending')}>{i===2?'Ready':'Review'}</span><button>Open</button></div>)}</div></section><section className="panel"><SectionTitle title="System health"/><div className="healthList"><div><span className="greenDot"/><div><strong>Authentication</strong><small>Operational</small></div></div><div><span className="greenDot"/><div><strong>Appointments</strong><small>Operational</small></div></div><div><span className="greenDot"/><div><strong>Messaging</strong><small>Operational</small></div></div></div></section><section className="panel span2"><SectionTitle title="Appointment volume"/><div className="bigChart"><div className="lineMock"><span/><span/><span/><span/><span/><span/><span/></div><div className="chartLabels"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></div></section><section className="panel"><SectionTitle title="Open support"/><div className="supportStats"><strong>18</strong><p>tickets awaiting response</p><span>Median first response: 14m</span></div></section></div></RoleShell>}

const adminCollections={
 '/admin/doctors':['Doctors','Verification, status and clinician profile management.','doctors'], '/admin/patients':['Patients','Patient account and support overview.','patients'], '/admin/appointments':['Appointments','Platform-wide appointment operations.','appointments'], '/admin/specialties':['Specialties','Clinical specialty directory management.','specialties'], '/admin/reviews':['Reviews','Moderate patient feedback and reported reviews.','reviews'], '/admin/payments':['Payments','Invoices, refunds and settlements.','payments'], '/admin/analytics':['Analytics','Operational growth and care activity.','analytics'], '/admin/support':['Support','Patient and clinician support requests.','support'], '/admin/users':['User status','Account states, verification and access controls.','users'], '/admin/audit':['Audit activity','High-sensitivity administrative activity log.','audit']
}
function AdminCollection(){const c=adminCollections[useLocation().pathname]; return <RoleShell role="admin" nav={adminNav}><AdminWorkspace title={c[0]} subtitle={c[1]} type={c[2]}/></RoleShell>}
function AdminWorkspace({title,subtitle,type}){const rows=type==='doctors'?doctors.map(d=>[d.name,d.specialty,d.location,'Verified']):type==='specialties'?specialties.map(s=>[s[0],s[1],`${Math.floor(Math.random()*80)+12} doctors`,'Active']):[['Amina Khan','Patient','Lahore','Active'],['Hassan Ali','Patient','Lahore','Active'],['Dr. Sarah Malik','Doctor','Lahore','Verified'],['Dr. Hira Sheikh','Doctor','Karachi','Review']]; return <><div className="contentHeader"><div><h2>{title}</h2><p>{subtitle}</p></div><Button><Plus/>Add new</Button></div>{type==='analytics'?<AdminAnalytics/>:<div className="tablePanel"><div className="adminToolbar"><div><Search/><input placeholder={`Search ${title.toLowerCase()}…`}/></div><Button variant="secondary">Export</Button></div><div className="responsiveTable"><div className="tableRow tableHead"><span>Name</span><span>Type / specialty</span><span>Context</span><span>Status</span><span></span></div>{rows.map((r,i)=><div className="tableRow" key={i}><span><strong>{r[0]}</strong><small>ID {1000+i*83}</small></span><span>{r[1]}</span><span>{r[2]}</span><span><span className={cls('badge',r[3].toLowerCase())}>{r[3]}</span></span><span><button>Manage</button></span></div>)}</div></div>}</>}
function AdminAnalytics(){return <div className="analyticsGrid"><Metric icon={Users} label="New patients" value="1,204" meta="Last 30 days"/><Metric icon={CalendarCheck} label="Booking conversion" value="71.8%" meta="+4.3 pts"/><Metric icon={Video} label="Video share" value="38%" meta="of consultations"/><Metric icon={Star} label="Avg. review" value="4.82" meta="12,860 ratings"/><section className="panel span2"><SectionTitle title="Monthly appointment trend"/><div className="bigChart tall"><div className="areaMock"></div></div></section><section className="panel span2"><SectionTitle title="Top specialties"/><div className="progressList">{[['General Medicine',84],['Cardiology',72],['Dermatology',64],['Pediatrics',58],['Psychiatry',49]].map(x=><div key={x[0]}><span>{x[0]}</span><div><i style={{width:`${x[1]}%`}}/></div><strong>{x[1]}%</strong></div>)}</div></section></div>}


function LiveRoleState({role,nav,children,demo}){
  const {session,profile,authLoading,authError}=useCare()
  if(authLoading)return <div className="portalLoading"><p>Loading secure workspace…</p></div>
  if(session&&authError)return <div className="portalLoading"><div className="notice" role="alert"><p>{authError}</p></div></div>
  if(session&&profile?.role&&profile.role!==role)return <Navigate to={'/'+profile.role} replace/>
  if(session&&profile?.status!=='active')return <div className="portalLoading"><div className="notice" role="alert"><p>This account is not active. Contact support for access.</p></div></div>
  if(session&&profile?.role===role)return <RoleShell role={role} nav={nav}>{children}</RoleShell>
  return demo
}
function PatientHomeRoute(){return <LiveRoleState role="patient" nav={patientNav} demo={<PatientDashboard/>}><PatientBackendDashboard/></LiveRoleState>}
function PatientCollectionRoute(){const cfg=patientCollections[useLocation().pathname]||patientCollections['/patient/records'];return <LiveRoleState role="patient" nav={patientNav} demo={<PatientCollection/>}><PatientBackendWorkspace type={cfg[2]}/></LiveRoleState>}
function DoctorHomeRoute(){return <LiveRoleState role="doctor" nav={doctorNav} demo={<DoctorDashboard/>}><DoctorBackendDashboard/></LiveRoleState>}
function DoctorCollectionRoute(){const cfg=doctorCollections[useLocation().pathname]||doctorCollections['/doctor/appointments'];return <LiveRoleState role="doctor" nav={doctorNav} demo={<DoctorCollection/>}><DoctorBackendWorkspace type={cfg[2]}/></LiveRoleState>}
function AdminHomeRoute(){return <LiveRoleState role="admin" nav={adminNav} demo={<AdminDashboard/>}><AdminBackendDashboard/></LiveRoleState>}
function AdminCollectionRoute(){const cfg=adminCollections[useLocation().pathname]||adminCollections['/admin/users'];return <LiveRoleState role="admin" nav={adminNav} demo={<AdminCollection/>}><AdminBackendWorkspace type={cfg[2]}/></LiveRoleState>}

function NotFound(){return <div className="notFound"><Logo/><span>404</span><h1>This page isn’t part of the care journey.</h1><p>Use the main navigation to return to a supported Medora experience.</p><Link className="btn btn-primary" to="/">Back home</Link></div>}

export default function App(){return <CareProvider><Routes>
  <Route path="/" element={<Home/>}/><Route path="/doctors" element={<FindDoctors/>}/><Route path="/doctors/:id" element={<DoctorProfile/>}/><Route path="/specialties" element={<Specialties/>}/><Route path="/how-it-works" element={<HowItWorks/>}/><Route path="/about" element={<About/>}/><Route path="/contact" element={<Contact/>}/><Route path="/faq" element={<FAQ/>}/><Route path="/login" element={<AuthPage/>}/><Route path="/register" element={<AuthPage register/>}/><Route path="/forgot-password" element={<AuthPage forgot/>}/>
  <Route path="/patient" element={<PatientHomeRoute/>}/><Route path="/patient/book" element={<BookingPage/>}/><Route path="/patient/appointments" element={<PatientAppointments/>}/>{Object.keys(patientCollections).map(p=><Route path={p} element={<PatientCollectionRoute/>} key={p}/>) }
  <Route path="/doctor" element={<DoctorHomeRoute/>}/>{Object.keys(doctorCollections).map(p=><Route path={p} element={<DoctorCollectionRoute/>} key={p}/>) }
  <Route path="/admin" element={<AdminHomeRoute/>}/>{Object.keys(adminCollections).map(p=><Route path={p} element={<AdminCollectionRoute/>} key={p}/>) }
  <Route path="*" element={<NotFound/>}/>
</Routes></CareProvider>}
